whitem4rk/2023-algorithm-study

- LEVEL 1/english_to_num.py
- LEVEL 1/mbti.py
- LEVEL 1/terms.py
- 2021 카카오 채용연계형 인턴십 / 숫자 문자열과 영단어 ( english_to_num.py )
- 2023 KAKAO TECH INTERNSHIP / 성격 유형 검사하기  ( mbti.py )
- 2023 KAKAO BLIND RECRUITMENT / 개인정보 수집 유효기간 ( terms.py )
> [Day 1]  LEVEL 1 3문제

- LEVEL 1/dart.py
- LEVEL 1/doll.py
- LEVEL 1/fail.py
- LEVEL 1/newid.py
- LEVEL 1/report.py
- LEVEL 1/treasure.py
- 2018 KAKAO BLIND RECRUITMENT / [1차] 비밀지도 ( treasure.py )
- 2018 KAKAO BLIND RECRUITMENT / [1차] 다트 게임 ( dart.py )
- 2021 KAKAO BLIND RECRUITMENT / 신고 결과 받기 ( report.py )
> [Day 2] LEVEL 1 3문제

- LEVEL 1/hamberger.py
- LEVEL 1/keypad.py
- LEVEL 1/lotto.py
- 2021 Dev-Matching: 웹 백엔드 개발자(상반기) / 로또의 최고순위와 최저순위
- 연습문제 / 햄버거 만들기
- 2020 카카오 인턴십 / 키패드 누르기
> [Day 4] LEVEL 1 3문제

- LEVEL 2/cache.py
- LEVEL 2/news.py
- LEVEL 2/tuple.py
- 2019 카카오 개발자 겨울 인턴십 / 튜플 (tuple.py)
- 2018 KAKAO BLIND RECRUITMENT / [1차] 뉴스 클러스터링 (news.py)
- 2018 KAKAO BLIND RECRUITMENT / [1차] 캐시 (cache.py)
> [Day 5] LEVEL 2 3문제

- LEVEL 2/bow.py
- LEVEL 2/delivery.py
- LEVEL 2/sale.py
- 2023 KAKAO BLIND RECRUITMENT / 택배 배달과 수거하기 (delivery.py)
- 2023 KAKAO BLIND RECRUITMENT / 이모티콘 할인행사 (sale.py)
- 2022 KAKAO BLIND RECRUITMENT / 양궁대회 (bow.py)
> [Day 6] LEVEL 2 3문제

- LEVEL 2/compress.py
- LEVEL 2/fee.py
- LEVEL 2/game.py
- LEVEL 2/prime.py
- LEVEL 2/queue.py
- LEVEL 2/rank.py
- LEVEL 2/relation.py
- LEVEL 2/zip.py
- 2021 KAKAO BLIND RECRUITMENT / 순위 검색 (rank.py)
- 2022 KAKAO TECH INTERNSHIP / 두 큐 합 같게 만들기 (queue.py)
실력이 없어서 푸는데 시간이 너무 오래걸려서 2문제밖에 못풀었습니다...
> [Day 7] LEVEL 2 2문제

- LEVEL 2/block.py
- LEVEL 2/calculate.py
- LEVEL 2/change.py
- LEVEL 2/chat.py
- LEVEL 2/filename.py
- LEVEL 2/partition.py
- LEVEL 2/renewal.py
- LEVEL 2/song.py
- LEVEL 3/shopping.py
- LEVEL 3/stone.py
- LEVEL 3/user.py
- 2018 KAKAO BLIND RECRUITMENT / [1차] 프렌즈4블록
- 2019 KAKAO BLIND RECRUITMENT / 오픈채팅방
- 2018 KAKAO BLIND RECRUITMENT / [3차] 파일명 정렬
> [Day 10,11,12] LEVEL 2 8문제

- LEVEL 3/(wrong)column.py
- LEVEL 3/advertise.py
- LEVEL 3/column.py
> [Day 16] LEVEL 3 2문제

- LEVEL 3/circle.py
- LEVEL 3/sheep.py
양과 늑대 (풀이를 봐도 이해를 못하겠어 도와줘 ㅠㅠ)
외벽 점검
> [Day 17] LEVEL 3 2문제

- LEVEL 3/bintree.py
- LEVEL 3/robot.py
> [Day 18] LEVEL 3 2문제

- LEVEL 3/miro.py
> [Day 19] LEVEL 3 1문제

- LEVEL 3/climb.py
> [Day 20] LEVEL 3 1문제

- LEVEL 3/matching.py
- LEVEL 3/traffic.py
> [Day 21,22] LEVEL 3 2문제

- LEVEL 3/merge.py
> [Day 23] LEVEL 3 1문제

- LEVEL 3/coding.py
> [Day 24] LEVEL 3 1문제

- LEVEL 1/budget.py
*프로그래머스로 첫 제출 정답 챌린지*
예산 (실패)
*리뷰 안해도됨
> [Day 25] LEVEL 1 1문제 

- LEVEL 1/average.py
- LEVEL 1/betweensum.py
- LEVEL 1/candivide.py
- LEVEL 1/dividesum.py
- LEVEL 1/hashad.py
- LEVEL 1/introot.py
- LEVEL 1/intsort.py
- LEVEL 1/kim.py
- LEVEL 1/kolatz.py
- LEVEL 1/oddeven.py
- LEVEL 1/pandy.py
- LEVEL 1/remain1.py
- LEVEL 1/revnum.py
- LEVEL 1/sumeach.py
- LEVEL 1/xiter.py
> [Day 26] LEVEL 1 15문제

- LEVEL 1/alldigin.py
- LEVEL 1/amusement.py
- LEVEL 1/delmin.py
- LEVEL 1/gcdlcm.py
- LEVEL 1/hatesame.py
- LEVEL 1/letterrev.py
- LEVEL 1/mulsum.py
- LEVEL 1/noexist.py
- LEVEL 1/phone.py
- LEVEL 1/plusminus.py
- LEVEL 1/rectanglestar.py
- LEVEL 1/rootsum.py
- LEVEL 1/rowcol.py
- LEVEL 1/takemid.py
- LEVEL 1/watermelon.py
> [Day 27] LEVEL 1 15문제

- LEVEL 1/alphatonum.py
- LEVEL 1/base3.py
- LEVEL 1/caesar.py
- LEVEL 1/cola.py
- LEVEL 1/foodfight.py
- LEVEL 1/idxk.py
- LEVEL 1/lesstwo.py
- LEVEL 1/minwallet.py
- LEVEL 1/mymindstring.py
- LEVEL 1/nearletter.py
- LEVEL 1/selectsum.py
- LEVEL 1/strangeletter.py
- LEVEL 1/threeman.py
- LEVEL 1/treasure2.py
- LEVEL 1/whichday.py
> [Day 28] LEVEL 1 15문제

- LEVEL 1/fail2.py
- LEVEL 1/findsosu.py
- LEVEL 1/makeprime.py
- LEVEL 1/moitest.py
- LEVEL 1/pocketmon.py
> [Day 29] LEVEL 1 5문제 

- LEVEL 1/dart2.py
- LEVEL 1/fruit.py
- LEVEL 1/honor.py
- LEVEL 1/lotto2.py
- LEVEL 1/mypair.py
- LEVEL 1/paint.py
- LEVEL 1/uniform.py
- LEVEL 1/weapon.py
> [Day 30] LEVEL 1 8문제

- LEVEL 1/bababab.py
- LEVEL 1/carddump.py
- LEVEL 1/divstring.py
- LEVEL 1/doll2.py
- LEVEL 1/keypad2.py
- LEVEL 1/marathon.py
> [Day 31] LEVEL 1 6문제

- LEVEL 1/hamberger2.py
- LEVEL 1/justpad.py
- LEVEL 1/mbti2.py
- LEVEL 1/newid2.py
- LEVEL 1/twocode.py
> [Day 32] LEVEL 1 5문제

- LEVEL 1/desktop.py
- LEVEL 1/park.py
- LEVEL 1/report2.py
- LEVEL 1/terms2.py
> [Day 32] LEVEL 1 4문제

- LEVEL 2/correctbracket.py
- LEVEL 2/jadencase.py
- LEVEL 2/makemin.py
- LEVEL 2/minmax.py
- LEVEL 2/rebin.py
> [Day 33] LEVEL 2 5문제

- LEVEL 2/carpet.py
- LEVEL 2/endword.py
- LEVEL 2/expressnum.py
- LEVEL 2/fib.py
- LEVEL 2/lifeboat.py
- LEVEL 2/nextbig.py
- LEVEL 2/pairremove.py
> [Day 34] LEVEL 2 7문제

- LEVEL 2/jumpportal.py
- LEVEL 2/nlcm.py
- LEVEL 2/tornerment.py
> [Day 35] LEVEL 2 3문제

- LEVEL 2/cache2.py
- LEVEL 2/hindex.py
- LEVEL 2/longjump.py
- LEVEL 2/rotatebracket.py
- LEVEL 2/tangerine.py
> [Day 36] LEVEL 2 5문제

- LEVEL 2/disguise.py
- LEVEL 2/rowcolmul.py
- LEVEL 2/slicen.py
- LEVEL 2/tuple2.py
> [Day 37] LEVEL 2 4문제

- LEVEL 2/funcdev.py
- LEVEL 2/news2.py
- LEVEL 2/printer.py
- LEVEL 2/seqsum.py
- LEVEL 2/targetnum.py
> [Day 38] LEVEL 2 5문제

- LEVEL 2/compress2.py
- LEVEL 2/dungeon.py
- LEVEL 2/phonebook.py
- LEVEL 2/prime2.py
- LEVEL 2/saleevent.py
> [Day 39] LEVEL 2 5문제

- LEVEL 2/eatland.py
- LEVEL 2/spicy.py
- LEVEL 2/stock.py
> feat: [LEVEL 2] 3문제

- LEVEL 2/chat2.py
- LEVEL 2/fee2.py
- LEVEL 2/game2.py
> [Day 40] LEVEL 2 3문제

- LEVEL 2/filename2.py
- LEVEL 2/skilltree.py
- LEVEL 2/visitlen.py
> [Day 41] LEVEL 2 3문제

- LEVEL 2/backtwo.py
- LEVEL 2/bignum.py
- LEVEL 2/bridgetruck.py
- LEVEL 2/twotile.py
> [Day 44] LEVEL 2 4문제

- LEVEL 2/changenum.py
- LEVEL 2/findprime.py
- LEVEL 2/makebig.py
- LEVEL 2/quadcompress.py
> [Day 45] LEVEL 2 4문제

- LEVEL 2/124.py
- LEVEL 3/allforone.py
- LEVEL 3/usingN.py
> [Day 46] LEVEL 2 1문제 | LEVEL 3 2문제

- LEVEL 2/miroexit.py
- LEVEL 3/doubleheap.py
- LEVEL 3/goschool.py
- LEVEL 3/triangle.py
> [Day 47] LEVEL 3 4문제

- LEVEL 3/connectisland.py
- LEVEL 3/diskcontrol.py
- LEVEL 3/farnode.py
- LEVEL 3/road2.py
- LEVEL 3/shopping2.py
- LEVEL 3/sticker2.py
- LEVEL 3/stone2.py
- LEVEL 3/taxi2.py
- LEVEL 3/travelway.py
- LEVEL 3/user2.py
> [Day 50] LEVEL 3 x문제
